
const MOCK_ISSUES = [
    // Bugs (Pending)
    {
        id: 101,
        iid: 1,
        project_id: 1,
        title: 'Fix login page crash on mobile safari',
        description: 'Login page crashes on submit when using Safari on iOS.',
        state: 'opened',
        created_at: new Date(Date.now() - 2592000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['bug', 'frontend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/1',
    },
    {
        id: 106,
        iid: 6,
        project_id: 1,
        title: 'Fix navigation menu on mobile',
        description: 'Menu does not collapse when clicking outside.',
        state: 'opened',
        created_at: new Date(Date.now() - 100000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['bug', 'frontend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/6',
    },
    {
        id: 111,
        iid: 11,
        project_id: 1,
        title: 'Fix typo in landing page',
        description: 'Correct "welocme" to "welcome".',
        state: 'opened',
        created_at: new Date(Date.now() - 600000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [],
        labels: ['bug', 'frontend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/11',
    },
    {
        id: 114,
        iid: 14,
        project_id: 1,
        title: 'Add unit tests for utils',
        description: 'Increase test coverage for utility functions.',
        state: 'opened',
        created_at: new Date(Date.now() - 900000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [],
        labels: ['bug', 'backend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/14',
    },
    {
        id: 115,
        iid: 15,
        project_id: 1,
        title: 'Fix broken link in footer',
        description: 'Terms of service link is 404.',
        state: 'opened',
        created_at: new Date(Date.now() - 1000000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['bug', 'frontend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/15',
    },

    // Features (Passed)
    {
        id: 102,
        iid: 2,
        project_id: 1,
        title: 'Implement Dark Mode toggle',
        description: 'Add dark mode support to the UI based on system preference.',
        state: 'opened',
        created_at: new Date(Date.now() - 172800000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [],
        labels: ['feature', 'frontend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/2',
    },
    {
        id: 103,
        iid: 3,
        project_id: 1,
        title: 'API rate limiting middleware',
        description: 'Implement rate limiting to prevent abuse.',
        state: 'opened',
        created_at: new Date(Date.now() - 86400000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['feature', 'backend'],
        web_url: 'https://gitlab.com/qa-hub/backend/-/issues/3',
    },
    {
        id: 107,
        iid: 7,
        project_id: 1,
        title: 'Add user profile page',
        description: 'Create a page for users to view and edit their profile.',
        state: 'opened',
        created_at: new Date(Date.now() - 200000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['feature', 'frontend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/7',
    },
    {
        id: 108,
        iid: 8,
        project_id: 1,
        title: 'Optimize image loading',
        description: 'Use lazy loading for images below the fold.',
        state: 'opened',
        created_at: new Date(Date.now() - 300000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [],
        labels: ['feature', 'frontend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/8',
    },
    {
        id: 110,
        iid: 10,
        project_id: 1,
        title: 'Update dependency versions',
        description: 'Update React and Next.js to latest versions.',
        state: 'opened',
        created_at: new Date(Date.now() - 500000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['feature', 'backend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/10',
    },
    {
        id: 112,
        iid: 12,
        project_id: 1,
        title: 'Implement search functionality',
        description: 'Add search bar to the header.',
        state: 'opened',
        created_at: new Date(Date.now() - 700000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['feature', 'frontend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/12',
    },
    {
        id: 113,
        iid: 13,
        project_id: 1,
        title: 'Refactor auth middleware',
        description: 'Simplify authentication logic.',
        state: 'opened',
        created_at: new Date(Date.now() - 800000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['feature', 'backend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/13',
    },

    // Critical (Failed)
    {
        id: 105,
        iid: 5,
        project_id: 1,
        title: 'Update payment gateway API key',
        description: 'Key rotation required.',
        state: 'opened',
        created_at: new Date(Date.now() - 43200000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [],
        labels: ['critical'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/5',
    },
    {
        id: 109,
        iid: 9,
        project_id: 1,
        title: 'Database connection timeout',
        description: 'Investigate intermittent connection timeouts.',
        state: 'opened',
        created_at: new Date(Date.now() - 400000000).toISOString(),
        updated_at: new Date().toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['critical', 'backend'],
        web_url: 'https://gitlab.com/qa-hub/frontend/-/issues/9',
    },
    {
        id: 104,
        iid: 4,
        project_id: 1,
        title: 'Legacy data migration script',
        description: 'Script to migrate old data to new schema.',
        state: 'opened',
        created_at: new Date(Date.now() - 604800000).toISOString(),
        updated_at: new Date(Date.now() - 86400000).toISOString(),
        author: { id: 1 },
        assignees: [{ id: 1 }],
        labels: ['critical', 'backend'],
        web_url: 'https://gitlab.com/qa-hub/backend/-/issues/4',
    },
];

const openIssues = MOCK_ISSUES.filter(i => i.state === 'opened');
console.log('Total Open Issues:', openIssues.length);

const boardLabels = ['bug', 'feature', 'critical'];
const issuesOnBoard = openIssues.filter(i => i.labels.some(l => boardLabels.includes(l)));
console.log('Issues on Board:', issuesOnBoard.length);

const missing = openIssues.filter(i => !i.labels.some(l => boardLabels.includes(l)));
console.log('Missing Issues:', missing.map(i => i.iid));

if (openIssues.length !== issuesOnBoard.length) {
    console.log('MISMATCH!');
} else {
    console.log('MATCH!');
}
